### ISSUE TITLE
check that 'disabled' states work for all items

### ISSUE THREAD

**Issue by Alexey-T** [Artem3213212/cuda_multi_installer#6]
pls, install all items. then check that 'disabled' state works for all.
(except data- lexers/snippets)

**Comment by Artem3213212** [comment]
только паскаль на котором тестировалось

**Comment by Artem3213212** [comment]
is_installed проверь я не знаю как ещё написать

**Comment by Alexey-T** [comment]
ладно, сам на винде проверю..
