### ISSUE TITLE
Need more decscription

### ISSUE THREAD

**Issue by kvichans** [Artem3213212/cuda_multi_installer#7]
Нашел единственную строку, которая поясняет работу плагина
`desc=Suggests to install add-ons for several popular languages`
Этого мало. Не понятно, что будет происходить.

Запустил, увидел
![default](https://user-images.githubusercontent.com/7419630/44576549-83ec4580-a797-11e8-9d37-cae03483900d.png)
Опять не понятно чего ожидать.

Почему набор языков ограничен этими? Если ли способ настроить список?

**Comment by Alexey-T** [comment]
надо поменять метку на более детальную- Select languages, later you can choose list of add-ons for selected langs.

**Comment by Alexey-T** [comment]
список настраивается мной в репозитории CudaText-registry.

**Comment by kvichans** [comment]
Непонятного много. Например, не ясно, как несколько галок в диалоге будут обработаны одним Next. Это психологически не удобно - не понимать, куда тебя ведут

**Comment by Alexey-T** [comment]
будет н диалогов по н выделениям, не писать же это.

**Comment by kvichans** [comment]
Лучше не делать "это". 
1. Сделать обычный listbox, а не checklistbox
2. Вместо Next, написать Choose ad-ons

Тогда станет понятно, что выбирать и для чего

**Comment by Alexey-T** [comment]
кнопка с капшеном Choose addons? кто так делает
чем checklistbox не ок?

**Comment by kvichans** [comment]
Претензия про психологию - "не комфортно". Дальше на ваше усмотрение

**Comment by Alexey-T** [comment]
простой listbox разве удобней. отмечать надо с чеками.

**Comment by kvichans** [comment]
ИМХО лучше дать возможность несколько раз вызывать плагин, чем запутать галками в списке языков

**Comment by Alexey-T** [comment]
плагин позволяет одним разом поставить аддоны для н языков.
